quarkus:
  http:
    port: 8081
  application:
    name: serverless-app
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: postgresql
    username: admin
    password: passw0rd
    jdbc:
      url: jdbc:postgresql://localhost:5432/demo
      max-size: 20

"%gcp":
  quarkus:
    http:
      port: 8080
    datasource:
      db-kind: postgresql
      username:
      password:
      jdbc:
        url: jdbc:postgresql:///postgres
        max-size: 20
        additional-jdbc-properties:
          cloudSqlInstance: dasea-lab:asia-east1:demo
          socketFactory: com.google.cloud.sql.postgres.SocketFactory
